# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
build:
working_directory: ~/Spring-recipe-book
docker:
  # specify the version you desire here
  - image: circleci/openjdk:8-jdk
steps:
  - checkout
  # Download and cache dependencies
  - restore_cache:
key: Spring-recipe-book-{‌{ checksum "pom.xml" }}
       - run: mvn install -DskipTests
       - run: mvn dependency:go-offline
       - save_cache:
paths:
  - ~/.m2
key: Spring-recipe-book-{‌{ checksum "pom.xml" }}
  # run tests!
  - run: mvn package
  - store_test_results:
path: target/surefire-reports
        - store_artifacts:
path: target/Spring-recipe-book-0.0.1-SNAPSHOT.jar